FIND_PATH(PORESCALE_INCLUDE_DIR porescale.hpp ${PORESCALE_ROOT}/include)
FIND_LIBRARY(PORESCALE_LIBRARY NAMES porescale PATHS ${PORESCALE_ROOT}/lib)
INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(PORESCALE DEFAULT_MSG PORESCALE_LIBRARY PORESCALE_INCLUDE_DIR)
